[package]
name = "nix-script"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.2.5", features = [ "std", "color", "suggestions", "derive", "cargo", "env" ] }
directories = "4.0.1"
directives = { path = "../directives" }
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.9.0"
once_cell = "1.12.0"
path-absolutize = "3.0.13"
seahash = "4.1.0"
serde_json = "1.0.81"
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "2.0.4"
rnix = "0.10.2"
tempfile = "3.3.0"
