[package]
name = "nix-script"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "3.2.23", features = [ "std", "color", "suggestions", "derive", "cargo", "env" ] }
directories = "5.0.1"
directives = { path = "../directives" }
lazy_static = "1.4.0"
log = "0.4.19"
env_logger = "0.10.0"
once_cell = "1.18.0"
path-absolutize = "3.1.0"
seahash = "4.1.0"
serde_json = "1.0.102"
walkdir = "2.3.3"

[dev-dependencies]
assert_cmd = "2.0.12"
rnix = "0.10.2"
tempfile = "3.6.0"
