[package]
name = "directives"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
log = "0.4.22"
rnix = "0.11.0"
rowan = "0.15.8"
serde = { version = "1.0.204", features = [ "derive" ] }
