[package]
name = "nix-script-haskell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.9", features = [ "std", "color", "suggestions", "derive", "cargo", "env" ] }
log = "0.4.16"
env_logger = "0.9.0"
