name: "Build and Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - uses: cachix/cachix-action@v8
        with:
          name: nix-script
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: niv
      - run: nix-env -if .
