name: "Build and Test"
on:
  pull_request:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      # - uses: cachix/cachix-action@v8
      #   with:
      #     name: nix-script
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      #     extraPullNames: niv
      - run: nix-build
      - run: |
          nix-env -if .

          # core tests
          (
            cd nix-script
            samples/test-has-script-file.hs
            samples/test-receives-arguments.hs a b c
            samples/test-has-runtime-input.hs
          )

          # clean up so we don't push test paths to cachix
          rm -rf .nix-script-cache
          nix-collect-garbage -d
