name: CI

on:
  push:

env:
  NIX_SCRIPT_LOG: trace
  NIX_SCRIPT_CACHE: cache

jobs:
  build-and-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - uses: cachix/cachix-action@v15
        with:
          name: nix-script
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: Swatinem/rust-cache@v2

      - run: nix build --print-build-logs
      - run: nix develop --command bash -c 'NIX_PATH="nixpkgs=$NIX_PKGS" cargo test'

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - uses: cachix/cachix-action@v15
        with:
          name: nix-script
          skipPush: true

      - run: nix develop --command rustfmt --check $(find . -name "*.rs" -not -ipath '*target*')
