name: CI

on:
  pull_request:
  push:

env:
  NIX_SCRIPT_LOG: trace
  NIX_SCRIPT_CACHE: cache

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        # note: we're using ubuntu-latest as a stand-in for all Linux
        # distributions. If we find we need more, we should do Docker stuff.
        os: [ubuntu-latest, macos-11] # depending on usage, maybe add macos-10.15 too
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: nix-script
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: Swatinem/rust-cache@v2

      - run: nix build --print-build-logs
      - run: nix develop --command bash -c 'NIX_PATH="nixpkgs=$NIX_PKGS" cargo test'

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: nix-script
          skipPush: true

      - run: nix develop --command rustfmt --check $(find . -name "*.rs" -not -ipath '*target*')
